### ISSUE TITLE
Regression: Extension suggesting incorrect values for apiVersions

### ISSUE THREAD

**Issue by edburns** [microsoft/vscode-azurearmtools#1004]
I observe #447 has regressed,

```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```

msazurermtools.azurerm-vscode-tools
0.12.0

arm-ttk says

```
Validating nestedtemplates\adminTemplate.json
    [+] adminUsername Should Not Be A Literal (128 ms)
    [-] apiVersions Should Be Recent (122 ms)
        Api versions must be the latest or under 2 years old (730 days) 
- API version 2018-10-01 of Microsoft.Compute/virtualMachines is 731 days old
        Valid Api Versions:
        2020-06-01
        2019-12-01
        2019-07-01
        2019-03-01
```

Same `[mainTemplate.json](https://github.com/wls-eng/arm-oraclelinux-wls/blob/73fd116f5031d4210f4bc7ff7e605eb19f8f9620/src/main/arm/mainTemplate.json)`.  Extension says:

```
For full schema validation, consider updating the value to one of the following: "2015-05-01-preview", "2015-06-15", "2016-04-30-preview", "2017-03-30", "2017-12-01", "2018-06-01", "2018-10-01", "2019-03-01", "2019-07-01". It is possible that the current resource version is valid but that a schema has not been generated. For more information see https://aka.ms/arm-tools-apiversion.
```

Why is the extension suggesting different version than ttk?

I know why: JSON schema out of date.  I continue to wonder if a better approach is not to have the extension query the Azure API instead?

**Comment by StephenWeatherford** [comment]
@edburns We don't just need the list of valid API versions, we also need the actual schemas for each of those versions in order to do schema validation, so querying the API for the valid versions isn't good enough.  With the new language server being written for Bicep, they are looking into some other possibilities like using the swaggers directly.

We also have a lag because we don't directly download the schemas, we ship them with the extension (we had various issues downloading directly, including inconsistent CDNs).  The new version which will ship next week shows the following:

For full schema validation, consider updating the value to one of the following: "2015-01-01", "2015-11-01", "2016-02-01", "2016-07-01", "2016-09-01", "2017-05-10", "2018-02-01", "2018-05-01", "2019-03-01", "2019-05-01", "2019-05-10", "2019-07-01", **"2019-08-01", "2019-10-01", "2020-06-01"**. It is possible that the current resource version is valid but that a schema has not been generated. For more information see https://aka.ms/arm-tools-apiversion.

The availability of new versions should be improving as they're doing more onboarding of automatic creation.  Sounds like we should ship hotfixes more frequently to reduce the lag, though.

**Comment by edburns** [comment]
I am happy with this resolution.  Closing.  Please re-open if desired.

**Comment by StephenWeatherford** [comment]
Thanks!
