### ISSUE TITLE
Can't get language server after build

### ISSUE THREAD

**Issue by v-tsun** [microsoft/vscode-azurearmtools#1154]
Hey team, 
I am trying to use this vscode-azurearmtools, but I can't get language server after run the build. I cloned your repo and ran script but some warning showed as below. 
![image](https://user-images.githubusercontent.com/73665970/106513064-48392800-6487-11eb-91a5-5b6ff131dcb0.png)
Looks like it doesn't get into the package process. In this case, is there are any prerequisite steps I need to do before getting language server or any steps I miss from there?

**Comment by StephenWeatherford** [comment]
@v-tsun This is due to current licensing restrictions on the language server, which uses code from VS (see https://github.com/microsoft/vscode-azurearmtools#license).  Due to that, packaging with the language server is restricted.

What are you trying to do?  If it's just a matter of making changes to use on your own machine, or to submit PRs, the easiest solution is to use the azureResourceManagerTools.languageServer.path to point to the language server from an existing installation of the extension (e.g. <user home>/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.14.0/languageServer).  

If that isn't sufficient, let me know what you're trying to accomplish and let me see how I can help.  Thanks.

**Comment by bganapa** [comment]
@StephenWeatherford We are from AzureStack Team and we are trying the ARMtools extension against AzureStack ARM. As AzureStack supports only a subset of Resource providers and older api versions, we may need some changes in the extension. We will likely get in touch with you if we figure out any issues that would need your inputs. At this moment @v-tsun  is just exploring this extension. Thanks for your quick response here!

**Comment by StephenWeatherford** [comment]
Sure thing, feel free to contact directly. Closing for now.

**Comment by StephenWeatherford** [comment]
@v-tsun BTW, this extension does not current sign in to Azure, it just edits ARM templates off-line, so not sure AzureStack makes any difference, unless there are different versions of the schemas.
