### ISSUE TITLE
Add a way to dynamically pull schemas

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/vscode-azurearmtools#1156]
Snapshot of the latest schema is manually copied to .zip which requires a new build to update. This should be pulled dynamically.

**Comment by StephenWeatherford** [comment]
The reasons for the current implementation:
1) Want a working extension if first run with no network connection (although that's compromised already if .net hasn't yet been downloaded for vscode)
2) Downloading hundreds of schemas separately is slow and error-prone, and we didn't have a good way of dealing with partially-correct sets of schemas
3) Regressions in schemas hit customers immediately with no way of working around the problem
4) CDN delivery seemed to be inconsistent - customers would get some schemas that don't match, causing errors (and difficult to repro, since we get different results each time and on different machines/networks)

**Comment by StephenWeatherford** [comment]
Consider picking up directly from azure schemas repo instead of published schemas, because published schemas can be updated infrequently.
