### ISSUE TITLE
Pop up a references dialog when pressing F12 on a parameter/variable name in the definition portion

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#1328]
**OS:** All
**Build Version:** 20210709.7

**Repro Steps:**

1. Load the `LoadBalancedVirtualMachine.json` file in the VS Code -> Click on a parameter name in the "parameters" portion of the file -> F12.
2. Check whether pop up a message.

**Expect:**
Pop up a message ‘`No definition found for "parametername“`’

**Actual:**
Pop up a references dialog to show all the usages of that parameter in the file.
![1](https://user-images.githubusercontent.com/62053665/125054067-64955c80-e0d8-11eb-82c7-1df23cd4777a.gif)

**More Info:**
This issue also reproduces for the variables.
![11](https://user-images.githubusercontent.com/62053665/125054078-66f7b680-e0d8-11eb-9f26-c5d217868ecf.gif)

**Comment by StephenWeatherford** [comment]
This is a change in behavior in vscode - since what you're clicking on *is* the definition, they used to give a message saying it couldn't find the definition (which was confusing).  They now simply show all references, which is much better.

I was going to change the testcase, but don't see that expected behavior in the testcase...?
