### ISSUE TITLE
String is longer than max length 24 and invalid warnings

### ISSUE THREAD

**Issue by asears** [microsoft/vscode-azurearmtools#1335]
When I have a valid ARM template, I see a few warnings which are not valid.  Is there a way to suppress these warnings or is that a feature that could be added?  These may also be bugs since the template is fine.

The first check validates the storage account name before parameter is evaluated, which will cause warning.

```json
 "resources": [
        {
            "name": "[parameters('storageAccountName')]",
```
This is a storage template.  Latest version of the template is 2021-02-01 so last two errors are invalid.  This is likely a limitation with full schemas vs. partial, however suppressing these errors at a file-level after review would be nice to have.

![image](https://user-images.githubusercontent.com/7253192/125783574-1fb86c99-21d9-4ef6-b153-6d43a0d818f4.png)

**Comment by StephenWeatherford** [comment]
@asears Thanks for taking the time to file a report.  Could you please try again with the new release from Tuesday (0.15.2)?
1. Supressing warnings is a feature we've considered but not committed to.  Please enter a separate issue if you'd like us to consider, but know that a lot of our resources right now are going to Bicep.
2. 2021-02-01 schema - this was fixed in 0.15.2
3. max length 24 - I don't see this problem in either 0.15.2 or earlier versions (see below sample).  Pretty sure this is an issue that was fixed a long time ago.  If you can repro with 0.15.2, can you send us a simple ARM template with just that resource that fails?  Thanks.
```arm
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageAccountName": {
            "type": "string"
        }
    },
    "functions": [],
    "variables": {},
    "resources": [
        {
            "name": "[parameters('storageAccountName')]",
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2021-04-01",
            "tags": {
                "displayName": "storageaccount1"
            },
            "location": "[resourceGroup().location]",
            "kind": "StorageV2",
            "sku": {
                "name": "Premium_LRS",
                "tier": "Premium"
            }
        }
    ],
    "outputs": {}
}
```
