### ISSUE TITLE
Need support for "static website" resources

### ISSUE THREAD

**Issue by brentarias** [microsoft/vscode-azurearmtools#1549]
Microsoft documentation explains how to create "static websites" with ARM templates, as shown [here](https://learn.microsoft.com/en-us/azure/static-web-apps/publish-azure-resource-manager?tabs=azure-cli) and [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/staticsites?pivots=deployment-language-arm-template).  This resource type has the designation `Microsoft.Web/staticSites`. However, the Azure Resource Manager extension for Visual Studio Code apparently has little or no metadata for this resource.

If I type `arm-web`, the extension's intellisense suggests `arm-web-app`.  If I select that, the resource type I'm given is `Microsoft.Web/sites`.  Otherwise, there is no option it suggests for creating a static website.

Why is this so?  When will the Azure Resource Manager Tool extension be modified to add this resource type?

Incidentally, if I simply paste sample static website resource notation into an ARM template, the ARM Tool seemingly does correctly provide intellisense for the properties.  Thus, it has at least partial knowledge of this resource type.

**Comment by StephenWeatherford** [comment]
@brentarias I'm assuming you're using the "Insert Item" context menu item to add new resources, right?  The list shown in that dropdown menu are resource *snippets*, i.e., they're a human-created set of best-practice examples for specific resources.  We have a limited number of them (but always happy to add more if we're provided quality snippet examples).

I agree this is confusing, we should at least change the wording to reflect this.

This is the same list that is shown if you just start typing inside the resources section:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/6913354/217046309-650b8cdc-7a20-4a5a-8252-672de5b44c3d.png">

As you note, the extension has knowledge of all resources specified in https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#,  including staticSites.  You can see this if you type the following inside "resources":
```json
{
  "type": "
```
and then press CTRL+SPACE, VS Code's standard shortcut for bringing up Intellisense:
<img width="972" alt="image" src="https://user-images.githubusercontent.com/6913354/217047033-269ff351-e8ac-453e-90a8-ea346a4ca1e0.png">
 
We don't add snippets for all resource types because we aren't experts in all the resource types and want the snippets we do have to guide people in the right direction by showing best-practice uses.  If you can provide quality snippets, we'd be happy to include them.  

Does this address your concerns?  Thanks!

**Comment by StephenWeatherford** [comment]
Also created this: https://github.com/microsoft/vscode-azurearmtools/issues/1553

**Comment by StephenWeatherford** [comment]
Given #1553 and the instructions above, closing this for now.  Feel free to reopen or open others issues if needed.
