### ISSUE TITLE
Microsoft.Web/sites schema seems out of date?

### ISSUE THREAD

**Issue by xstof** [microsoft/vscode-azurearmtools#305]
When trying to get intellisense when authoring a template for a web app, the latest version of the schema which the tooling seems to accept (for which it gives intellisense) is "2016-08-01".  Meanwhile the latest version published seems to be [2018-11-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-11-01/sites)

Can we fix intellisense for web apps please?

**Comment by StephenWeatherford** [comment]
I definitely feel your frustration here.  There are multiple issues at stake, one of them being that the full schemas as just too large for the current tools to handle well.  We're actively working on a better experience here, hopefully it will be available soon.

**Comment by StephenWeatherford** [comment]
@ifeoluwaokunoren I thought the most recently available schema was supposed to be in the published schema, is that not the case?

**Comment by ifeoluwaokunoren** [comment]
Hi @StephenWeatherford, 
That would be the case if the team is onboarded to the autogeneration pipeline but the web team isn't. I have asked the microosft.web team to look into this issue since they're responsible for generating this missing schema. I have also  asked the team to onboard to the autogeneration pipeline to avoid such issues going forward.

**Comment by StephenWeatherford** [comment]
Thanks!  Is there a way we can track that progress?

**Comment by marckassay** [comment]
@StephenWeatherford Do you know when all schema related will be resolved? I believe you mentioned mid-November?

**Comment by StephenWeatherford** [comment]
We just shipped a version of the extension that should make the experience much better, in that:
1) If there are errors, we give you a better idea of what the fixes actually are (as opposed to suggesting that you change the resource type, for instance)
2) Fixes many false positives due to things like case sensitivity
3) Gives better intellisense

Please try it out!

Unfortunately, there are still issues in the actual Azure schemas that they're trying to fix, largely by making the schema creation process more automated.  I can't answer on when exactly all of those will be fixed, they'll be done on an ongoing basis, please continue to post issues.

**Comment by marckassay** [comment]
@StephenWeatherford, thanks for prompt reply! I look forward using it when the schema issues are resolved.

**Comment by ifeoluwaokunoren** [comment]
This PR should fix this issue - https://github.com/Azure/azure-resource-manager-schemas/pull/761

As at today, we have about 58 services that are onboarded to the schemas autogeneration pipeline. I'm currently working with the Microsoft.Web team to get them to onboard, that way when changes are made to the swagger specs, the ARM autogeneration pipeline picks up those changes on a daily basis. 

FYI: @naveedaz, @pvbchak, @ruslany

**Comment by neilpeterson** [comment]
I've validated that this looks good now, thanks @ifeoluwaokunoren .

![image](https://user-images.githubusercontent.com/7844635/73101613-e07bf480-3ea4-11ea-919a-ac5d5062e89d.png)

I've also [updated the extension snippets](https://github.com/microsoft/vscode-azurearmtools/pull/451) so that the lates version is used. This update should be included with the next extension release.

Thanks again @xstof for raising the issue.
