### ISSUE TITLE
JSON formatting change in 0.7.0

### ISSUE THREAD

**Issue by EwanNoble** [microsoft/vscode-azurearmtools#339]
In v0.6.0 of the extension empty arrays would be formatted like so:
![image](https://user-images.githubusercontent.com/22656473/67292825-6d489800-f4db-11e9-88e4-fa4f56fa42a6.png)

In v0.7.0 they are now formatted as:
![image](https://user-images.githubusercontent.com/22656473/67292877-83eeef00-f4db-11e9-8f4c-293e0680ee36.png)

Is this intended or a bug?
Thanks

**Comment by StephenWeatherford** [comment]
We've switched to a new language server that uses code from VS.  This change was not intentional, but we knew there might be minor changes in behavior.  Does this change concern you?

**Comment by EwanNoble** [comment]
I wouldn't say it's a major problem, however VSCode JSON formatter would have formatted it as per the first image, so I do wonder if something is going wrong there if the intention is to use their code?

**Comment by StephenWeatherford** [comment]
Nothing's wrong, it's just a difference in preference in certain cases.  We changed settings to it mostly matches vscode as far as we can tell.  I'm going to close for now since it doesn't sound like you're saying it needs to be fixed.  Thanks for letting us know, though, and feel free to let me know if you disagree.
