### ISSUE TITLE
There is no a prompt asking when opening a template file with a 2018-05-01 schema

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurearmtools#374]
**OS**: All
**Build Version**: [20191101.29](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11981)
**Regression:** Not a Regression

**Repro Steps:**
1. Get a template file with below schema from https://github.com/bmoore-msft/arm-template-language-samples like "schema-expresions-everywhere.json".

"$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#"

2. Open it in VS Code.
3. Check whether pop up a prompt asking or not.

**Expect:**
Pop up a prompt asking like below.
![image](https://user-images.githubusercontent.com/34729092/68113432-c62e1c80-ff2e-11e9-9bc6-993ca7904ee4.png)

**Actual:**
There is no a prompt asking.

**Comment by StephenWeatherford** [comment]
Thanks, that's expected, because there is not a more recent subscription deployment schema.  The only two schemas that are old and have an updated version are the resource group deployment schemas:
- schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json and 
- schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json

**Comment by v-dantch** [comment]
Got it. Thanks for your share and we will update it for our test case.
