### ISSUE TITLE
Use NSG for virtual network in snippets?

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-azurearmtools#454]
See https://devdiv.visualstudio.com/DevDiv/_git/AT-ServiceFabricTools/pullrequest/223870?_a=files

**Comment by StephenWeatherford** [comment]
Particularly this comment:
> Ravikumar Palanisamy
> @Stephen Weatherford FYI. You may have to do similar change to ARM template.

**Comment by neilpeterson** [comment]
With this PR, I have added NSG to the VM snippets.

https://github.com/microsoft/vscode-azurearmtools/pull/522

An NSG can be associated either with a VNET (subnet) and / or a NIC. I'm assuming there may be some cases where a VNET would be created without an associated NSG. 

Options:

- Updated the VNET snippet so that it also adds the NSG and association.
- Update the VNET snippet so that it has a place holder for an NSG association. We would also ensure that the current NSG snippets aligns so that if both are added, the association works OOB.
- Leave the current snippets alone and add a new one `vnet-nsg` that adds the VNET, NSG, and association.
