### ISSUE TITLE
"Working..." info problem anti-pattern

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#463]
Extension version 0.8.3

I noticed you're using an info diagnostic as an indicator to the user than the extension is warming up or something:

![image](https://user-images.githubusercontent.com/2193314/73275333-d2c3b900-419b-11ea-83d0-f1d20843e100.png)

Typically for this sort of thing extensions add a status bar item while it's working or nothing and a notification only if something went wrong.

I'm also curious why it takes so long to do its thing? This happened after hitting use latest schema on a notification which changed the file to use a schema that was definitely already good to use as I had been working on a template in another window just fine.

/cc @misolori in case you have more thoughts on extensions loading/starting UX before diagnostics/intellisense start working.

**Comment by StephenWeatherford** [comment]
Nobody ever seems to notice status bar items (myself included), IMHO it's extremely ineffective as a means of letting the user know what's going on (I wish it weren't).  We have four different sources where errors can come from, one of them can be very slow, especially if we have to download schemas from the Internet first, and also depending on file size.  If we show three sources and then it waits a long time to show the fourth, it implies that those are the only errors.  

I don't see any disadvantages to doing it this way, but am open to other ideas.  The message comes up any time that validation takes longer than a couple of seconds.

**Comment by Tyriar** [comment]
@StephenWeatherford personally a status bar item that pops up is far more prominent to me than a tiny 1 character blue squiggle. The main point is that pretty much every other extension follows an established pattern of status bar items for this sort of loading action (when it's called for). VS Code even does this itself:

![image](https://user-images.githubusercontent.com/2193314/73309963-294ee880-41d8-11ea-83c3-8c44df73e79b.png)

**Comment by misolori** [comment]
Besides using a status bar item (which several extensions already use), you could show a notification when you detect it's taking longer than expected. That is really the best way to get the user's attention and is a common pattern we use as well as others. We do also show a "Loading..." item for IntelliSense before data has been loaded, in case it's been used there.

I'd avoid creating anti-patterns like using the diagnostics view to show progress as it will confuse users since this isn't a pattern.

**Comment by StephenWeatherford** [comment]
> far more prominent to me than a tiny 1 character blue squiggle

It's not the blue squiggle we care about but the info in the Issues panel that gets their attention, but only if they're actually currently looking for errors.

> We do also show a "Loading..." item for IntelliSense before data has been loaded, in case it's been used there.

Right, you show it where the user will see it and where they're expecting data to be filled in, and not in a notification like you're suggesting for this similar scenario.  The issues list is where they're looking for the information.  Seems like a notification would be distracting if they're not currently looking at the errors list, especially since it will come up frequently the first time an ARM file is loaded in a session.  At least a notification would actually be noticeable, which status bar changes aren't.

@neilpeterson Thoughts?

**Comment by neilpeterson** [comment]
@StephenWeatherford took a look at the experience, and have given it some thought. My preference would be to use common patterns and while I agree, status bar may not be super noticeable, it's an ok and common experience.

**Comment by StephenWeatherford** [comment]
Fixed as part of linked template work.
