### ISSUE TITLE
Prettier cannot format azuredeploy.json when Azure ARM tools installed

### ISSUE THREAD

**Issue by pmcilreavy** [microsoft/vscode-azurearmtools#465]
When Azure ARM tools installed and enabled my default code formatter (Prettier) is unable to format any json file which contains an ARM schema definition. When formatting is attempted the following message is visible in the toolbar: "Extension 'Prettier - Code Formatter' cannot format 'azuredeploy.json'"

If the Azure ARM tools extension is disabled then Prettier is able to format the document as expected. Something about the Azure ARM tools extension is preventing Prettier from being able to format the document.

**Comment by StephenWeatherford** [comment]
@pmcilreavy A few versions ago we switched to a dedicated language server for ARM template files, which allows us to do a much better job with validation and intellisense than the default JSON language server.  In order to get the language server to work for JSON files in vscode, we have to use a dedicated language ID.  By default we switch automatically when we detect an ARM schema, as you'll see in the status bar:
![image](https://user-images.githubusercontent.com/6913354/73317284-6c19bc00-41ea-11ea-8a5b-64a0ac591007.png)
I.e., it's technically no longer a JSON file, so the prettier doesn't know about it.

Possible solutions:
1) Preferably: Log a bug against the prettier extension and request that they support the "arm-template" language ID (and treat it as a JSON file)
2) Check if there's a way to configure the prettier extension to disable itself for arm-template language ID documents. We have our own document formatter that kicks in for arm-template files.
3) Turn off automatic switching to the arm-template language ID by disabling vscode setting azureResourceManagerTools.autoDetectJsonTemplates. Then you can switch the editor back to JSON to format with prettier and switch again to arm-template to enable ARM support.

Not sure why vscode doesn't automatically use our formatting if prettier fails - don't know if that's vscode's fault or prettier's fault.

**Comment by StephenWeatherford** [comment]
@neilpeterson Would it be worth it to find the formatting extensions in vscode that support JSON and make sure they support arm-template?

**Comment by neilpeterson** [comment]
@StephenWeatherford as discussed I will look closer a this and compare with some similar extensions.

**Comment by bergmeister** [comment]
I tried to configure `prettier to use the `arm-template` language using the following setting:
```
[arm-template]": {
     "editor.defaultFormatter": "esbenp.prettier-vscode"
},
```
But prettier fails then, not sure who is to blame but I wouldn't be surprised if the prettier extension has the `json` or `jsonc` language hard-coded somewhere...

**Comment by ntotten** [comment]
I commented on the issue on the vscode prettier extension on how to actually [fix this in prettier itself](https://github.com/prettier/prettier/blob/master/src/language-js/index.js#L39-L66). The other option is to use the `.prettierrc` to override.

```
{
  "overrides": [
    {
      "files": "azuredeploy.json",
      "options": {
        "parser": "json"
      }
    }
 ]
}
```

**Comment by bergmeister** [comment]
@ntotten Thanks. because the ARM template file name can be anything and not just `azuredeploy.json`, the 2nd provided workaround is unfortunately not very practical for most repos.
 I've tried to open a new PR in prettier, can you have a look please: https://github.com/prettier/prettier/pull/8274

**Comment by neilpeterson** [comment]
Closing this in lieu of the PR on the prettier project. Thanks for opening this and working with the prettier project.
