### ISSUE TITLE
Add auto-complete / IntelliSense for the resourceId() function

### ISSUE THREAD

**Issue by neilpeterson** [microsoft/vscode-azurearmtools#491]
After declaring the `resourceId()` function, provide a list of resources found in the current template.

```
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', 'nepetersone')]",
                "[resourceId('Microsoft.Storage/storageAccounts', variables('name'))]"
            ]
        }
    ],
    "outputs": {
        "resourceId": {
            "type": "string",
            // Same IntelliSense experience everywhere
            "value": "[resourceId('Microsoft.Storage/storageAccounts', 'nepetersone')]"
        }
    }
}
```

**Comment by StephenWeatherford** [comment]
**Development notes:**
- [ ] First arg - show completions for resource types used in template, deduped, alphabetized
- [ ] Second arg - show completions for names of resources in the template that use that resource type
- [ ] Third/other args - special for child resources
- [ ] Do we complete in the middle of an arg expression?
- [ ] extensionResourceId, tenantResourceId, subscriptionResourceId, ~~managementGroupResourceId~~ or resourceId ("Depends on the scope of the template.  So for example, if you're in a subscription scoped template, you'd use subscriptionResourceId.  Tenant scope, then tenantResourceId()")
Spec Issues: 
- [ ] Copy blocks ("you can use the name of a copy loop as a dependency (i.e. the entire loop instead of a single resource)... autocomplete should list those too")
- [ ] Resource types with more than two segments
- [ ] dependsOn completion, or just resourceId?
- [ ] Child resources (examples: https://github.com/neilpeterson/arm-template-collection/tree/master/3-other/resource-id-child-resources)
  - [ ] Do we allow references to child resources?
  - [ ] Does resourceId completion behave differently when inside a child resource?
- [ ] "a P2 would be to warn on if() statements in dependsOn... people add them (they work) but are never needed."
- [ ] Do we auto-complete with concat() when inside a dependsOn?
- [ ] Do we auto-complete for reference?  e.g. "value": "[reference(concat('Microsoft.Network/publicIPAddresses/', variables('agentIPAddressName'))).dnsSettings.fqdn]"

**Comment by neilpeterson** [comment]
Few notes after playing with this a bit.

**Resource ID for child resource with concat function**

We do not appear to be handling decoupled child resources that use the concat function in the name. I believe this would be a relatively common configuration. [This template](https://github.com/neilpeterson/arm-template-collection/blob/master/1-priority-work-examples/child-resource-diff-resource-api/azuredeploy-decoupled.json) can be used to reproduce.

The proper format for the child resource should be:

```
"[resourceId('Microsoft.Sql/servers/firewallRules',variables('sqlServer'),variables('firewallRuleName'))]"
```

However we produce this:

```
"[resourceId('Microsoft.Sql/servers/firewallRules',concat(variables('sqlServer'), '/' , variables('firewallRuleName')))]"
```

**Sticky Function Signature**

Perhaps this is the proper behavior, if so, feel free to ignore. It seems like when completing the resourceId function, we leave the cursor just inside of the function, which leaves the function signature visible.

![image](https://user-images.githubusercontent.com/7844635/78614116-88f1f180-7822-11ea-99f3-0b39a2b3a10e.png)

Compare that with the variable function. Once we complete the function, the cursor is placed just outside of the function, which automatically removes the signature.

**Spaces**

Can we automatically add spaces between the function segments?

![image](https://user-images.githubusercontent.com/7844635/78614223-da01e580-7822-11ea-8f46-36d751245ff9.png)

Would become:

![image](https://user-images.githubusercontent.com/7844635/78614284-09185700-7823-11ea-9e2d-0b99b0ac27be.png)

**Comment by StephenWeatherford** [comment]
> Resource ID for child resource with concat function
Implemented

> Sticky Function Signature
TypeScript intelligente doesn't do this.  I think it would be confusing in the same way that automatically adding "()" was confusing - touch typists will expect to close it themselves, if we do it they'll end up with two.

> Spaces
Ditto I don't think that's our job.  I think this would be better handled by format document.

**Comment by StephenWeatherford** [comment]
Fixed by https://github.com/microsoft/vscode-azurearmtools/pull/580, except for https://github.com/microsoft/vscode-azurearmtools/issues/626
