### ISSUE TITLE
Signature help gets confused by additional sets of brackets

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#502]
Starting point:

![image](https://user-images.githubusercontent.com/2193314/75096549-7e6ee780-5555-11ea-973f-caf68d5f7e41.png)

`(` (not expected):

![image](https://user-images.githubusercontent.com/2193314/75096553-86c72280-5555-11ea-9f29-8c86f5172d6a.png)

`)` (also not expected):

![image](https://user-images.githubusercontent.com/2193314/75096557-9b0b1f80-5555-11ea-87ab-dc7143676b36.png)

**Comment by StephenWeatherford** [comment]
@Tyriar Don't think I understand what you're suggesting should happen here.  Additional sets of parentheses are an error during deployment, if I remember correctly.  What's your expected behavior?  Thx.

**Comment by Tyriar** [comment]
It's unclear to me what the second screenshot should be, the third one should show signature help for parameters, not concat

**Comment by StephenWeatherford** [comment]
ARM expression language doesn't allow wrapping an arbitrary expression with parentheses. Thus, the expression is invalid, and our parser considers the first closed parenthesis to close the parameters function call. In that sense, this is by design.  Either way, it's of minor impact so I don't think it warrants any more time.  Nevertheless, thanks for filing this and the other issues!
