### ISSUE TITLE
[Feature] Provide capability to navigate to ARM template reference documentation

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-azurearmtools#590]
Would be nice to see functionality similar to [PowerShell extension](https://github.com/PowerShell/vscode-powershell), but for ARM templates.

Preview of functionality:
![AzureResourceManagerRecommendation](https://user-images.githubusercontent.com/25514145/79090063-72620380-7d16-11ea-88fe-4b40065debbd.gif)

Would be good if Azure resources were available like above, that also linked to [documentation reference](https://docs.microsoft.com/en-us/azure/templates/).

This would make the ARM template development workflow much easier.

**Comment by neilpeterson** [comment]
Thanks @rrmistry. We will triage / prioritize where it makes sense and where we are able.

**Comment by nilshedstrom** [comment]
Not exactly what was requested but the implementation of #508 will probably contain a list of the 66 something snippets that can be used to create resources.
![image](https://user-images.githubusercontent.com/785949/79489951-60d17200-801c-11ea-8ceb-c191cc3e0a3c.png)
So not all possible resources and no link to documentation but atleast a list of the snippets.

**Comment by nilshedstrom** [comment]
This seems interesting so I would like to implement this.
@neilpeterson: How can I get a list of all resource types with documentation at https://docs.microsoft.com/en-us/azure/templates/ ? 
Calling Get-AzResourceProvider or parsing the schemas downloaded by the language server gives me some resource types that does not have documentation.
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Web/sites/extensions as an example when parsing the schemas.

**Comment by StephenWeatherford** [comment]
@rrmistry Just to make sure, were you aware of the snippet functionality?  I.e., pressing CTRL+SPACE and then "arm-" to see the list of resource snippets?  (Still would like to see something along these lines implemented.)

> This would make the ARM template development workflow much easier.

Can you elaborate on how you would see the workflow here?  Is it more about adding new resources like via the snippets?  Is it about seeing documentation for existing resources?  Etc.  Thanks.

**Comment by StephenWeatherford** [comment]
@nilshedstrom I think the best way is probably to have the language server provide the extension a list of all the resource types it's discovered from the schema, we can implement that without too much trouble.  We've considered doing that for resourceId/etc intelligente anyway.

@alex-frankel Do you know why documentation would be missing for resources, e.g. https://docs.microsoft.com/en-us/azure/templates/Microsoft.Web/sites/extensions as Nils noted above?

**Comment by rrmistry** [comment]
Regarding:

> Can you elaborate on how you would see the workflow here? Is it more about adding new resources like via the snippets? Is it about seeing documentation for existing resources? Etc. Thanks.

At the moment, the number of resources available via snippets seems limited and difficult to extend.

Example workflow for a hypothetical new developer first trying Azure:
1. Create Azure Function resource
1. Create dependent Azure Storage Account (after discovering requirement in schema)
1. Create App Insights and Log Analytics workspace resource after some research
    1. Link original Azure Function with Log Analytics workspace via diagnostics settings as a sub-resource
1. Adding App Service site extensions as sub-resource using `/providers/{...}`
1. etc.

Being able to search for schemas and available properties on (most likely existing) specific resources seems more helpful than ability to insert a semi-complete snippet only good for general use cases.

A view like this with ability to drill-down to individual properties would be so helpful:
![Resources](https://github.com/microsoft/vscode-azureresourcegroups/blob/master/resources/readme/explorer.png?raw=true)

Thanks,

**Comment by nilshedstrom** [comment]
@StephenWeatherford and @neilpeterson:
To me it seem like most of the documentation for [Storage Accounts](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2018-07-01/storageaccounts#Microsoft.Storage/storageAccounts) is generated from its [schema](https://github.com/Azure/azure-resource-manager-schemas/blob/master/schemas/2018-07-01/Microsoft.Storage.json).
So if we got access to the schema from the language server then we could possibly generate the documentation and show it in a web view inside vscode. So the advantage is that we have more control of how the documentation looks like, do not have to show it in an external browser and do not rely on internet connectivity. The downside is that it is more work.
Since not all resource types we have in the schemas are available on https://docs.microsoft.com/en-us/azure/templates another option would be to parse that page and look for links looking like https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2018-07-01/storageaccounts and have that as a source for resource types with documentation. The advantage is that we will only show resources with documentation and is less work to implement. The downside is that we rely on the existance of that page.

**Comment by neilpeterson** [comment]
I believe the docs are built from Swagger but in comparing a few Swagger docs to generated schemas, it looks like schemas have everything that we would need.

A few notes on using existing docs:

- The PowerShell extension currently opens docs in a browser (for comparison sake)
- One thing I use ARM reference docs for quite often is to explore parent / child resources which can be done using doc navigation. This would require additional effort to mimic in VS Code.
- Docs include links to examples, which may also be helpful.

![image](https://user-images.githubusercontent.com/7844635/80986677-bf9d3680-8de5-11ea-955d-a3857c5e5f5b.png)

**Comment by nilshedstrom** [comment]
So it seems like opening an exernal browser would be a good thing.
But what would be the best source of available resource types?
* Reading from schemas (might not be in sync with the documentation available on https://docs.microsoft.com/en-us/azure/templates )
* Parsing https://docs.microsoft.com/en-us/azure/templates and looking for links
* Hard coded list in the plugin (will always work but might become out of sync)
* Combination: Schema or parsing website as first option and hard coded list as second option.

**Comment by neilpeterson** [comment]
@tfitzmac we are considering options for linking to docs from the ARM Tools VS Code extension. It seems like there is a well-defined structure for resource / api version = doc.

- root - https://docs.microsoft.com/en-us/azure/templates/
- (namespace, api version, resource) - microsoft.network/2019-05-01/frontdoors

https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-05-01/frontdoors

Beyond guessing based on this convention do you have any thoughts on how we could build the docs url (assuming we know the namespace, api version, and resource name)?

Thanks

**Comment by tfitzmac** [comment]
@neilpeterson - if you want to go directly to a particular API version, the URL you suggested is probably the best way. There are a couple of other things you could consider:

1. I am in the process of adding a "Latest" folder for each resource provider. It would include the latest API version for each resource type so you don't have to hunt for resource types if they are split across different versions. The URL would never change; it would always be - Microsoft.network/frontdoors. From that link, a user could always navigate to a specific version. If users are linking to the docs when adding a new resource type, it would make sense to always link them to the latest version. If they are linking from an existing resource definition that uses an API version, it might make more sense to go to the version. For an idea of how it will work, look at [https://docs.microsoft.com/en-us/azure/templates/microsoft.addons/supportproviders/supportplantypes](https://docs.microsoft.com/en-us/azure/templates/microsoft.addons/supportproviders/supportplantypes).

2. I need to rework the doc generation process. We might be able to come up with some way of coordinating what is presented in docs with what is presented in VS Code. Could we come up with an endpoint that returns the published versions?

**Comment by neilpeterson** [comment]
Thanks @tfitzmac. For point 2, yes we should coordinate on this. Let me know when you are queuing up the work and I will get involved.

@nilshedstrom how do you feel about 'guessing' on the URL based on the convention detailed above? 

I've also noticed that each namespace has an all versions doc, perhaps if we cannot find an apiVersion specific doc we can open the all versions doc. Here is [an example](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/allversions).

Workflow could be similar to:

- Check for internet connection, if true proceed, if false do nothing.
- Check for existence of apiVersion / resource doc, if true open, if false proceed.
- Check for existence of namespace / all versions doc, if true open, if false do nothing

**Comment by nilshedstrom** [comment]
When I look at the page https://docs.microsoft.com/en-us/azure/templates/
> If you know the resource type, you can go directly to it with the following URL format: https://docs.microsoft.com/azure/templates/{provider-namespace}/{resource-type}. For example, the SQL database reference content is available at: https://docs.microsoft.com/azure/templates/microsoft.sql/servers/databases

So following the conventions above should be in line with the documentation on the page.

Something that is a little bit of "guessing" would be to link to the "root" of the documentation like this https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts#Microsoft.Storage/storageAccounts
or to a specific part https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts#Sku
We could open a browser with the last link if the user wants to show documentation for the Sku property inside a storage account.
If the structure of that page changes the links will still work but the browser will not scroll to the optimal location.

Should I start implementing this (maybe using a hard coded list of resource types) or wait untill the endpoint mentioned by @tfitzmac  is ready?

**Comment by StephenWeatherford** [comment]
@neilpeterson @nilshedstrom What's the proposed UI?  I.e., where/how does the user request to view documentation?

**Comment by neilpeterson** [comment]
Nils has suggested using go to deffiniton to produce docs vs produce resource schemas. Suggestion is in [this issue](https://github.com/microsoft/vscode-azurearmtools/issues/648).

I'm not sure if this would be a misuse of the [go to definition functionality](https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition) but I think it's worth thinking through.

**Comment by nilshedstrom** [comment]
Go to definition would be one way. But I prefer the following ways
* Editor context menu "Show Documentation..." that will will open a dialog with the available resource types. When the user selects a resource type a browser will open a page with the documentation for that resource type (latest version) [example](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts#Microsoft.Storage/storageAccounts)
* ARM template outline: Context menu and inline icons (similar to Insert Resource...). Then the browser would display the documentation for the specified resource using the apiVersion of that resource. [Example](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts#Microsoft.Storage/storageAccounts).
If the user selects "Show documentation" for the Sku in the storage account a browser would open that scrolls to the Sku section. [Example](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts#Sku). This would be a "best effort" approach since the documentation is not always consistent.

**Comment by tfitzmac** [comment]
Is this the [type of data](https://github.com/tfitzmac/TemplateTests/blob/master/published-resource-types.json) you would want returned from the endpoint? I didn't include all of the API versions, but you'll get the idea of how it would work.

**Comment by nilshedstrom** [comment]
@tfitzmac 
Looks good. I am not sure we have a need for subheaders.
How would we know the following non trivial mappings from property to subheader
* properties => StorageAccountPropertiesCreateParameters
* restrictions => Restriction
* networkAcls => NetworkRuleSet
* services => EncryptionServices
* virtualNetworkRules => VirtualNetworkRule
* ipRules => IPRule
* blob => EncryptionService
* file => EncryptionService

Can you estimate how big the full response would be? 
It we cannot really use the subheaders it might slow down the request without any benefit.

**Comment by tfitzmac** [comment]
The response would be per resource type, so storage account would be about 10 KB (4 times its current size). I would imagine some the networking resource types could be fairly large.

In the long run, I could change the doc generation process to include different subheaders. It could use the property name. I believe the current values come from a label in the REST API specification.

**Comment by neilpeterson** [comment]
@nilshedstrom Stephen and I noodle around with this a bit today.

**Navigation to specific resource@apiVersion docs**

- editor context menu > show documentation - could we inspect the current location of the cursor and if within a resource, navigate to docs for the appropriate resource@apiVersion combo. If a doc is not found (404), navigate to the latest version that Tom had mentioned above.

- ARM Template Outline - context menu / button to open resource@apiVersion combo. Totally agree with this. For property-specific navigation (best effort), if you get into this and find that it's not worth the effort or the accuracy is not good, I think there is still a lot of value in only navigating to the root of the doc. Keeping it simple would be my vote over extra effort / inaccurate results. 

**Navigation to the latest versioned doc for any resource (doc browser)**

For a doc browser type experience, as Stephen mentioned above, we may be able to get a list of resources from the language server.

- editor context menu > show documentation - if we were to implement the above resource-specific context menu, would we need a second one to initiate the 'doc browser'? Can we explore options to make it a single context menu entry?

- ARM Template Outline - context menu and inline icon on the resources node. Sound like the right move to me.

**Comment by neilpeterson** [comment]
This issue is heavy on docs. The initial issue also had an element of inserting resources (comparison to PowerShell extension).

I think it may make sense to rename / rescope this issue to reflect providing a doc navigation experience.

We have work planned to revisit / improve snippets. When done, this work should address the second part of this issue. Here is the first scheduled item for the snippet improvement work:

https://github.com/microsoft/vscode-azurearmtools/issues/654

@rrmistry if you have any concerns with this let me know and we will adjust.

**Comment by nilshedstrom** [comment]
@tfitzmac When parsing the schemas I found a resource type Microsoft.Web/sites/extensions that does not have any [documentation](https://docs.microsoft.com/en-us/azure/templates/Microsoft.Web/sites/extensions). Do you think there are many resource types without documentation?

@neilpeterson When looking at the current editor context menu items
![image](https://user-images.githubusercontent.com/785949/82264956-30a42880-9966-11ea-9d28-a787d5d46c26.png)
None of them are context aware (it does not matter where in the file you invoke them). So for me it does not make sense to add a "Show Documentation"-item there that depends on the location of the cursor. I think it makes more sense to have a general "Show Documentation..." item that will show the list of resource types and after the user selects a resource type the page with documentation will be opened in a browser.

At the moment it seems like linking to the [property values](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts#Microsoft.Storage/storageAccounts) of the documentation is the best approach. If we try to link to the correct heading and fail the user will go to the [top](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts) of the page which is worse (I think) than always scrolling to the property values location.

When you think we can get the resource types from the language server?

**Comment by neilpeterson** [comment]
Thanks Nils, makes sense.

I will start talking with the team this week about the language server interface for providing a list of resources. I've opened a separate work item to track.

https://github.com/microsoft/vscode-azurearmtools/issues/718

**Comment by tfitzmac** [comment]
@nilshedstrom - I'll take a look at that resource type to see why it is not in the docs.

@neilpeterson - If I can get the same list of resource types, then I can audit the docs against the resource types VS Code expects to see. We would not need an endpoint that returns the published resource types, because VS Code could assume the types are published.

**Comment by MarcusFelling** [comment]
@nilshedstrom Is this something you are still interested in working on?

**Comment by nilshedstrom** [comment]
> @nilshedstrom Is this something you are still interested in working on?

I created a [small implementation](https://github.com/nilshedstrom/vscode-azurearmtools/tree/showDocumentation) last year lets start discuss it since I do not have time to do some huge other implementation.

It registers a new command "showDocumentation" that will show a quickPick-dialog where the user can select/filter the resource type to display documentation about. After the selection a new browser is opened with the documentation for the selected resource type.

The showDocumentation command is accessible through context menu in the editor and "ARM template outline".
You can also access it with icons in "ARM template outline"
![image](https://user-images.githubusercontent.com/785949/109158683-fcbb2680-7773-11eb-8be9-a329524dc8c8.png)
![image](https://user-images.githubusercontent.com/785949/109158732-0ba1d900-7774-11eb-8348-ddfebf2f8d00.png)

I would like to add the posibility to navigate to a resource in the "ARM template outline" and then show the documentation for that resource type (not selecting resource type in a dialog). Possibly also navigate to the correct API version.

@neilpeterson Can we get the resource type from the language server?

**Comment by StephenWeatherford** [comment]
@nilshedstrom Good to hear from you again.  Sorry, should have mentioned - Neil Peterson has moved to a different project.  @MarcusFelling is now working on this project with me (as well as the bicep project).

Yes, I can provide the info we need from the language server.  I'm assuming we just need:
- List of all resource types and API versions
Anything else you need?

**Comment by nilshedstrom** [comment]
Hi! 
I noticed that some resource types still does not have documentation. Here is a few random ones that does not have documentation
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Sql/locations/administratorAzureAsyncOperation
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Sql/locations/capabilities
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Sql/locations/longTermRetentionBackups
https://docs.microsoft.com/en-us/azure/templates/microsoft.support/services
https://docs.microsoft.com/en-us/azure/templates/Microsoft.DBforPostgreSQL/locations/checkVirtualNetworkSubnetUsage
https://docs.microsoft.com/en-us/azure/templates/Microsoft.ServiceBus/sku
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Sql/servers/recommendedElasticPools
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Sql/locations/syncDatabaseIds
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Sql/servers/jobAccounts
https://docs.microsoft.com/en-us/azure/templates/Microsoft.Cache/locations

So it would be good to figure out why these resource types does not have documentation and only return the resource types that do have documentation.

**Comment by StephenWeatherford** [comment]
@nilshedstrom How did you generate your list of resources?  It seems to contain extraneous resources.  For instance, for SQL locations, I only see these:

![image](https://user-images.githubusercontent.com/6913354/109237389-47de3500-7786-11eb-88fc-9818862d3d5a.png)

Both of those have documentation.  This is the list I assume you'd like to get from the language server.

**Comment by nilshedstrom** [comment]
I was using the script https://github.com/nilshedstrom/vscode-azurearmtools/blob/showDocumentation/tools/updateResourceTypes.ps1 that use Get-AzResourceProvider.

But if I only get resource types with documentation from the language server that is great.
What is the code to get the resource types from the language server?

**Comment by StephenWeatherford** [comment]
I have to write it for you, the language server is unfortunately not open source.  Will try to get something for you soon.

**Comment by StephenWeatherford** [comment]
Depends on #1258

**Comment by StephenWeatherford** [comment]
@nilshedstrom That took longer than I'd hoped - been spread somewhat thin.  You can either use the alpha at https://github.com/microsoft/vscode-azurearmtools/releases/tag/v0.15.1-alpha ("F1 -> Install from VSIX...") or wait until the 0.15.1 release, should be early next week.

See src/languageclient/getAvailableResourceTypesAndVersions.ts for the API.
