### ISSUE TITLE
Experience editing exported templates from Azure is still lacking

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-azurearmtools#643]
This happened while trying to make a site name exported from a template on azure generic:

![29ee63ab-48eb-4ce1-80ac-03d682c95605](https://user-images.githubusercontent.com/2193314/80230044-3710e000-8606-11ea-9f9a-44d78ba6d7f4.gif)

I see the following issues that prevent this experience being great:

- No syntax highlighting until the final `]` was placed (I don't write language extensions, maybe this is complicated?)
- `concat` got signature help and intellisense/function details, but `parameters` did not
- Completing `'appservice_name'` deleted everything to the right of it, making me either need to remember what it said and re-type or undo to check. https://github.com/microsoft/vscode-azurearmtools/issues/127

**Comment by neilpeterson** [comment]
Thanks @Tyriar. I believe we have an existing issue for the third point (linking here for cross-reference).

https://github.com/microsoft/vscode-azurearmtools/issues/127

**Comment by StephenWeatherford** [comment]
I'm concentrating on Intellisense bugs and usage this milestone, so keep these coming!

**Comment by StephenWeatherford** [comment]
The first issue (no colorization until typing the end bracket) is due to the fact that a string that starts with "[" but does not end with "]" is considered a valid string by ARM, not an expression with an error.  In fact, there's an interesting valid scenario for this when using Chef:

I.e., deploy the following:
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
    ],
    "outputs": {
        "output1": {
            "type": "string",
            "value": "[ChefInSpec]InstalledApplicationLinuxResource1;AttributesYmlContent"
        }
    }
}

```
Deploys successfully with
```
"outputs": {
      "output1": {
        "type": "String",
        "value": "[ChefInSpec]InstalledApplicationLinuxResource1;AttributesYmlContent"
      }
    },
```
That scenario is currently handled correctly by colorization (meaning it colorizes as a string, not an expression), but not by the expression validation (meaning it should give no errors, but it actually does give errors - see https://github.com/microsoft/vscode-azurearmtools/issues/250).

Unfortunately, if you try to escape the opening "[" with "[[" (https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions#escape-characters), it doesn't work - "[[" only works if the string also ends in "]". E.g.:
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "resources": [
    ],
    "outputs": {
        "output1": {
            "type": "string",
            // Try escaping the starting '[' with '[[' 
            "value": "[[ChefInSpec]InstalledApplicationLinuxResource1;AttributesYmlContent"
        }
    }
}
```
yields the original [[ in the string:
```
"outputResources": [],
    "outputs": {
      "output1": {
        "type": "String",
        "value": "[[ChefInSpec]InstalledApplicationLinuxResource1;AttributesYmlContent"
      }
    },
```

It might be worth lying in this scenario...  Perhaps the extension should consider ```"[opening bracket"``` to be an expression with an error, but ```"[opening and closing] bracket"``` to be a string and thus no error?  That allows the Chef scenario to work as expected.  The work-around if you really need ```"[opening bracket"``` to be a string would be to use an expression with a string literal: ```"['[opening bracket']"```.  (Unfortunately, that is also not currently handled by the extension - we currently require a function at the top level, although we could fix that, or they could use concat :-( ).  

Colorization also has no concept of where the cursor is, so that context doesn't help.

@bmoore-msft @neilpeterson Thoughts?

**Comment by StephenWeatherford** [comment]
I do agree that not having the colorization for an unfinished expression is a little irksome.

**Comment by Tyriar** [comment]
> Perhaps the extension should consider "[opening bracket" to be an expression with an error, but "[opening and closing] bracket" to be a string and thus no error?

This seems like a good idea. Provided the errors you mention are purely syntax highlighting errors (not diagnostics) then it could lead to wrong coloring in the tiny amount of cases where the string starts with `[` but does not contain a closing `]`, but greatly benefit writing out expressions manually.

**Comment by StephenWeatherford** [comment]
Note: This scenario only occurs with an existing string - if you type `"` and `[`, the the `]` and `"` are added automatically.

**Comment by bmoore-msft** [comment]
I tend to think about optimizing for the common case...  the vast majority of the time when I start with a bracket in a string (existing too), I'm writing an expression.  So having the tooling throw in the closing ] before the end quote would help in the majority of cases.  In the rare case, where I don't want that closing bracket, I can delete it.

**Comment by Tyriar** [comment]
@bmoore-msft that behavior depends on this setting `"editor.autoClosingBrackets"`, the default is to insert it.

**Comment by bmoore-msft** [comment]
I think that's for the empty/new string scenario...  I want the behavior on any string.  I.e. if I put an opening bracket after the opening quote, I want the extension to insert a closing bracket before the closing quote (regardless of what's in between).

**Comment by StephenWeatherford** [comment]
I think I'll have to add that behavior manually when the string already exists, but it would solve the problem...

**Comment by StephenWeatherford** [comment]
@Tyriar @bmoore-msft After looking at this, I'm not sure there's a way (or that it's desirable) to automatically insert the closing bracket reliably.  I was able, though, to provide a snippet:
![tostring](https://user-images.githubusercontent.com/6913354/88746653-e24b9c80-d101-11ea-8f31-c7d56fa57880.gif)
Does this do what you want (you can press TAB to enter the snippet)?

Note that currently if you select the entire string and then press "[", vscode will adding the [] pair around the selection.

Note also we plan to add an "extract to parameter/variable" feature soon.  Also, would love to hear any other ideas, see #787 for current things we're thinking about.  Thanks!

**Comment by Tyriar** [comment]
I'm no expert on writing language extensions. This in TypeScript is the behavior I wanted, not removing `after`:

![recording (19)](https://user-images.githubusercontent.com/2193314/89103366-3090c200-d3c6-11ea-8150-02fadd99cb00.gif)

**Comment by bmoore-msft** [comment]
I think the "end" described in the additional issue is still the same (IMO) - if take the example of I have literal value of:

"someResourceName"

And I want to turn that into a resourceId... but leave the literal part.  I would insert the opening bracket and start typing "resourceId(" but would get not autocomplete for it since it's not yet considered an expression...  If we turned it into an expression straight-away I get all the goodness of autocomplete for resourceId (and in this case dependsOn).

I tried to figure out the short-cut for selecting a property value text and didn't figure it out :b - I think the refactoring will help, but only in the scenario where I'm converting to param/var which won't catch quite a few scenarios...

**Comment by StephenWeatherford** [comment]
This was becoming quite confusing, broke this out into separate bugs:

Expressionifying strings: Need better experience editing existing string to make it an expression #902
Expressionifying strings: Completing 'appservice_name' deleted everything to the right of it #903
Expressionifying strings: No syntax highlighting until the final `]` is placed #900
Expressionifying strings: concat got signature help and intellisense/function details, but parameters did not #901
