### ISSUE TITLE
There is an endless loop between "Type a parameter name" and "Select a type of parameter"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurearmtools#765]
**OS:** Mac
**Build:** 20200604.33

**Repro Steps:**

1. Open a template file in VS Code.
2. F1 --> Type and select "Insert Item..."  --> Select "Function" --> Type a function name --> Select a type of location output --> Type a parameter name.

**Expect:**
End the "insert item" action after "Type a parameter name".

**Actual:**
There is an endless loop between "Type a parameter name" and "Select a type of parameter".
![image](https://user-images.githubusercontent.com/62053665/83849584-39587500-a742-11ea-8265-b1198ca3adfa.png)

**More info:**
It will End the "insert item" action if press enter when 'Type a parameter name".

**Comment by StephenWeatherford** [comment]
This is by design - users can enter zero or multiple parameters.  But i agree it could be confusing, changed the prompts a little to this:

![image](https://user-images.githubusercontent.com/6913354/83903387-e3b8a400-a712-11ea-913b-42189031a78a.png)
![image](https://user-images.githubusercontent.com/6913354/83903414-ee733900-a712-11ea-9b3d-d92ae97c4348.png)
