### ISSUE TITLE
List function is not recognized

### ISSUE THREAD

**Issue by konopkap** [microsoft/vscode-azurearmtools#949]
List function is not recognized by extension although it works correctly in ARM Template
![image](https://user-images.githubusercontent.com/52398735/92593870-25bd2d00-f2a2-11ea-8e8f-5a5504550746.png)

**Comment by StephenWeatherford** [comment]
@bmoore-msft I wasn't aware of a function "list" without a suffix, and don't see it documented at https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions?

**Comment by konopkap** [comment]
@StephenWeatherford It's document as **List* ** under resource functions

Here you can see that valid use of list* function with Microsoft.Web/sites/config is just "list"
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#valid-uses

**Comment by StephenWeatherford** [comment]
I was aware of the list* functions, but not of a list function (no suffix).  Is it possible to call "list" with more than 2 parameters (like for instance listAccountSas has)?

**Comment by bmoore-msft** [comment]
Yes, the shape of the request is up to the RP... so it could be 0..n - I think we're hitting the limit of what we can provide for intellisense/autocomplete without parsing the functions params for the resourceType and having a lot more metadata about the shape of the api.

True for "list" but also true for any "list*" function because the resourceId is part of the uri in the raw API request.
